### ISSUE TITLE
HELP WITH HOMEKIT SONOFF BASIC PASSWORD

### ISSUE THREAD

**Issue by igorcmiranda** [LuuTinhIT/Homekit#1]
Hello,

I have tried the password but is not working for me. In your post you said that you can help if we pass the mac and device. 
Can you help me?

My mac is: 70:03:9f:6a:f4:a2
My device is: Sonoff Basic R2

**Comment by LuuTinhIT** [comment]
Trying download and flash again. I had uploaded newest version with 888-88-888 pass

**Comment by LuuTinhIT** [comment]
close with newest version
